// <auto-generated />
using System;
using Infrastructure.EntityFrameworkDataBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221214105459_CreateModels")]
    partial class CreateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Movies.MovieLibraryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("MovieLibraries");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Movies.MoviePlayerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaRoomId")
                        .IsUnique();

                    b.ToTable("MoviePlayers");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Movies.MovieType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieLibraryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieLibraryTypeId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.ChatRoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaRoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaRoomTypeId");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.CinemaRoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId")
                        .IsUnique();

                    b.ToTable("CinemaRooms");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.GuestCinemaRoomInvitation", b =>
                {
                    b.Property<int?>("CinemaRoomTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("UserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CinemaRoomTypeId", "UserTypeId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("GuestCinemaRoomInvitation");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.MessageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Users.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieLibraryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieLibraryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Movies.MoviePlayerType", b =>
                {
                    b.HasOne("Infrastructure.EntityFrameworkDatabase.Models.Rooms.CinemaRoomType", "CinemaRoom")
                        .WithOne("MoviePlayer")
                        .HasForeignKey("Infrastructure.EntityFrameworkDatabase.Models.Movies.MoviePlayerType", "CinemaRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaRoom");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Movies.MovieType", b =>
                {
                    b.HasOne("Infrastructure.EntityFrameworkDatabase.Models.Movies.MovieLibraryType", "MovieLibrary")
                        .WithMany("Movies")
                        .HasForeignKey("MovieLibraryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieLibrary");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.ChatRoomType", b =>
                {
                    b.HasOne("Infrastructure.EntityFrameworkDatabase.Models.Rooms.CinemaRoomType", "CinemaRoom")
                        .WithMany()
                        .HasForeignKey("CinemaRoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaRoom");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.CinemaRoomType", b =>
                {
                    b.HasOne("Infrastructure.EntityFrameworkDatabase.Models.Users.UserType", "Admin")
                        .WithOne("AdminCinema")
                        .HasForeignKey("Infrastructure.EntityFrameworkDatabase.Models.Rooms.CinemaRoomType", "UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.GuestCinemaRoomInvitation", b =>
                {
                    b.HasOne("Infrastructure.EntityFrameworkDatabase.Models.Rooms.CinemaRoomType", "CinemaRoom")
                        .WithMany("Guests")
                        .HasForeignKey("CinemaRoomTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Infrastructure.EntityFrameworkDatabase.Models.Users.UserType", "User")
                        .WithMany("guestCinemas")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CinemaRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.MessageType", b =>
                {
                    b.HasOne("Infrastructure.EntityFrameworkDatabase.Models.Rooms.ChatRoomType", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Users.UserType", b =>
                {
                    b.HasOne("Infrastructure.EntityFrameworkDatabase.Models.Movies.MovieLibraryType", "MovieLibrary")
                        .WithMany()
                        .HasForeignKey("MovieLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieLibrary");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Movies.MovieLibraryType", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.ChatRoomType", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Rooms.CinemaRoomType", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("MoviePlayer")
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.EntityFrameworkDatabase.Models.Users.UserType", b =>
                {
                    b.Navigation("AdminCinema")
                        .IsRequired();

                    b.Navigation("guestCinemas");
                });
#pragma warning restore 612, 618
        }
    }
}
